=== alummanuelgarcia/xml/xmlLab/ejercicio2.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/ejercicio2.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE listalibros SYSTEM "ejercicio2.dtd">

    <listalibros>
    ...
    </listalibros>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT listalibros (libros)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT libros (autores|titulo|editorial|publicacion|ISBN)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT autores (autor)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT autor (apellido1|apellido2|nombre)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT apellido1 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT apellido2 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT titulo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT editorial (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT publicacion (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ISBN (#PCDATA)>

=== alummanuelgarcia/xml/xmlLab/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listalibros SYSTEM "ejercicio2.dtd">

<listalibros>
    <libros>
        <autores>
            <autor>
                <apellido1>Lopez</apellido1>
                <apellido2>Rodriguez</apellido2>
                <nombre>Carmen</nombre>
            </autor>
            <autor>
                <apellido1>Perez</apellido1>
                <apellido2>Sanchez</apellido2>
                <nombre>Ana</nombre>
            </autor>
        </autores>
        <titulo>Microeconomia</titulo>
        <editorial>Ed. de economia</editorial>
        <publicacion>Abril 2010 </publicacion>
        <ISBN>1-232-541-21</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Jimenez</apellido1>
                <apellido2>Amaya</apellido2>
                <nombre>Raul</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>La guerra</titulo>
        <editorial>Puerta</editorial>
        <publicacion>Diciembre 1990</publicacion>
        <ISBN>9-587-188-98</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Gutierrez</apellido1>
                <apellido2>Lopez</apellido2>
                <nombre>Juan</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Problemas en la granja</titulo>
        <editorial> Lopez Editorial</editorial>
        <publicacion>Febrero 2010</publicacion>
        <ISBN>9-658-548-51</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Sanchez</apellido1>
                <apellido2>Amaya</apellido2>
                <nombre>Ana</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Julio en Primavera</titulo>
        <editorial>Trente</editorial>
        <publicacion>Junio 2009</publicacion>
        <ISBN>5-895-554-55</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Yumi</apellido1>
                <apellido2>Mingoya</apellido2>
                <nombre>Paula</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Navidad Embrujada</titulo>
        <editorial>Trente</editorial>
        <publicacion>Diciembre 2004</publicacion>
        <ISBN>4-987-654-87</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Huescar</apellido1>
                <apellido2>Lopez</apellido2>
                <nombre>Lola</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Juan Williams</titulo>
        <editorial>Saco Oro</editorial>
        <publicacion>Octubre 2007</publicacion>
        <ISBN>9-266-215-54</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Williams</apellido1>
                <apellido2>Carrey</apellido2>
                <nombre>Jonh</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Sometimes cry</titulo>
        <editorial>Door</editorial>
        <publicacion>Diciembre 2009</publicacion>
        <ISBN>5-874-965-85</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Jimenez</apellido1>
                <apellido2>Fernandez</apellido2>
                <nombre>Raul</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Fernandez Castillo</titulo>
        <editorial>Trente</editorial>
        <publicacion>Junio 2002</publicacion>
        <ISBN>2-652-523-55</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Maradona</apellido1>
                <apellido2>Armando</apellido2>
                <nombre>Diego</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Amor Argentina</titulo>
        <editorial>Argentina Collections</editorial>
        <publicacion> Junio 1990</publicacion>
        <ISBN>8-515-622-55</ISBN>
    </libros>
    <libros>
        <autores>
            <autor>
                <apellido1>Jimenez</apellido1>
                <apellido2>Amaya</apellido2>
                <nombre>Ana</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>La estrategia</titulo>
        <editorial>Ocaso</editorial>
        <publicacion>Marzo 2001</publicacion>
        <ISBN>5-325-215-55</ISBN>
    </libros>
</listalibros>
