<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ediciones_aranda 
[
<!ELEMENT ediciones_aranda (cabecera, tabla)>
<!ELEMENT cabecera (titulo,contenido,descripcion,fecha)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tabla (region+,trimestre,libros_vendidos)>
<!ELEMENT region (norte|centro|sur)>
<!ELEMENT norte (#PCDATA| trim|lib)*>
<!ELEMENT centro (#PCDATA| trim|lib)*>
<!ELEMENT sur (#PCDATA| trim|lib)*>
<!ELEMENT trim (#PCDATA)>
<!ELEMENT lib (#PCDATA)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT libros_vendidos (#PCDATA)>
]>
<ediciones_aranda>
    <cabecera>
        <titulo>Ediciones Aranda </titulo>
        <contenido>Informe Regional de ventas </contenido>
        <descripcion>Descripcion: informe de ventas para las regiones</descripcion>
        <fecha> Fecha: 30/12/2009 </fecha>
    </cabecera>
    <tabla>
        <region>
            <norte> Norte 
            
            
            
            
            </norte>       
        
         </region>   
              
     </tabla>
